### ISSUE TITLE
Update Rails app skeleton

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/was-registrar-app#1]

**Comment by jcoyne** [comment]
Should this be an API only Rails app, or should it have HTML views too?

**Comment by justinlittman** [comment]
This will have both API and HTML views.

**Comment by jcoyne** [comment]
Please make a determination of doing a JSON API (via rails) and a javascript UI (like RIALTO) or if we're going to generate HTML in Rails (like pre-assembly).

I prefer the former approach, because it separates the UI concerns from the business logic (a problem we've faced in many apps).

**Comment by justinlittman** [comment]
Given that this app will have 2 pages and no client-side scripting requirements, HTML in Rails is sufficient.
