### ISSUE TITLE
API for setting last crawl month

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/was-registrar-app#12]
So that robot can update.

**Comment by jcoyne** [comment]
How will the caller identify which collection they want to update?

**Comment by aaron-collier** [comment]
DRUID makes the most sense I think. As the collection creation requires a druid and it is not constrained as unique.

**Comment by jcoyne** [comment]
what is "last crawl month"?  Is that a property of Collection?  Does it need to be added to the model or is it the same as `last_successful_fetch`?

**Comment by aaron-collier** [comment]
It is `last_successful_fetch`
