### ISSUE TITLE
Register seeds with Argo

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/was-registrar-app#124]
From @nullhandle:

```
we need to confirm that argo is sufficient for initiating either the crawl or seed pre-assembly workflows
i tried using argo to initiate the seed pre-assembly workflow and ran into an error: https://argo.stanford.edu/view/druid:jk262gy2296
i think that it's looking for a dummy xml metadata template that is bundled with the legacy was-registrar app
```

**Comment by justinlittman** [comment]
The following shows the steps of the wasSeedPreassemblyWF:
![Screen Shot 2019-08-30 at 9 26 21 AM](https://user-images.githubusercontent.com/588335/64024424-55bae780-cb08-11e9-9c69-14c2d6614af1.png)

The [build-was-seed-druid-tree](https://github.com/sul-dlss/was_robot_suite/blob/master/robots/wasSeedPreassembly/build_was_seed_druid_tree.rb) step expects a seed file in `/was_unaccessioned_data/seed/<druid>.xml`. Here is an example of that file:
```
<?xml version="1.0"?>
<item>
  <druid_id>druid:zz845pg7580</druid_id>
  <collection_id>druid:sr233xh9483</collection_id>
  <source_id>sul:ARCHIVEIT-EAL-8001-www.econ.keio.ac.jp/</source_id>
  <uri>http://www.econ.keio.ac.jp/</uri>
  <source>G</source>
  <embargo>false</embargo><source_xml/>
</item>
```
This file is copied and renamed.

The [desc-metadata-generator](https://github.com/sul-dlss/was_robot_suite/blob/master/lib/was_seed_preassembly/desc_metadata_generator_service.rb) steps loads the seed file and based on the value of `source`, selects an XSLT template, performs a transform, and writes a descriptive metadata file.

Note:
* All source values except "G" have been [deprecated](https://consul.stanford.edu/display/WARC/Initiating+Seed+Object+Accessioning).
* The only values that the [G XSLT](https://github.com/sul-dlss/was_robot_suite/blob/master/template/wasSeedPreassembly/descMetadata_G.xslt) uses are `uri` and `collection_id`.

The next step is the [thumbnail generator](https://github.com/sul-dlss/was_robot_suite/blob/master/robots/wasSeedPreassembly/thumbnail_generator.rb). It loads the seed file to get the `uri`.

None of the other steps use the seed file.

**Comment by justinlittman** [comment]
Thus, if the need for the seed file was obviated, then seeds could be registered with Argo.

This would require:
1. Remove support for sources other than "G".
2. Remove copying / manipulation of the seed file.
3. When data (uri, collection id) is needed, get that data from DOR services instead of the seed file.

It appears that uri and collection id can be extracted from the MODS and the MODS is available from DOR Services Client (`object.metadata.descriptive`).

Here's an example:
```
<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<mods xmlns=\"http://www.loc.gov/mods/v3\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" version=\"3.6\" xsi:schemaLocation=\"http://www.loc.gov/mods/v3 http://www.loc.gov/standards/mods/v3/mods-3-6.xsd\">\n  <titleInfo>\n    <title>URI ---> http://teachinghumanrights.org/</title>\n  </titleInfo>\n  <relatedItem type=\"host\">\n    <titleInfo>\n      <title>Individual Archived Websites</title>\n    </titleInfo>\n    <location>\n      <url>COLLECTION--->https://purl.stanford.edu/cr827qv5481</url>\n    </location>\n    <typeOfResource collection=\"yes\"/>\n  </relatedItem>\n  <accessCondition type=\"useAndReproduction\">Access is provided in a manner consistent with the Stanford University Libraries Web Archiving Policy (https://library.stanford.edu/projects/web-archiving/policy).</accessCondition>\n</mods>\n
```

**Comment by justinlittman** [comment]
Based on discussion with @jcoyne, parsing the needed fields from the MODS is not optimal. And preferred approach is to expose a JSON endpoint (see https://github.com/sul-dlss/dor-services-app/pull/288) that will provided the needed fields.

Again, the needed fields are:
* URL (from identityMetadata objectLabel)
* Collection (from RELS-EXT fedora:isMemberOfCollection)

**Comment by justinlittman** [comment]
Depends on:
* https://github.com/sul-dlss/workflow-server-rails/issues/244
* https://github.com/sul-dlss/was_robot_suite/issues/144
* https://github.com/sul-dlss/was_robot_suite/issues/145
* https://github.com/sul-dlss/was_robot_suite/issues/146
* https://github.com/sul-dlss/was_robot_suite/issues/147

**Comment by nullhandle** [comment]
Attempts to register seeds in Argo and have them complete the workflow have not been successful.

See https://argo-stage.stanford.edu/view/druid:pw330pt3699 and https://argo.stanford.edu/view/druid:jk262gy2296.

Access points for these seeds are present in the stage and production SWAP instances, respectively: https://swap-stage.stanford.edu/*/http://www.stanford.edu and https://swap.stanford.edu/*/http://teachinghumanrights.org, so the workflow should at least not be failing for that reason.

**Comment by justinlittman** [comment]
For https://argo-stage.stanford.edu/view/druid:pw330pt3699: SWAP (https://swap-test.stanford.edu/) is incorrectly configured or not running.

For https://argo.stanford.edu/view/druid:jk262gy2296: Looks like the workflow completed correctly. I think the error that is displayed is an error that occurred while I was testing the workflow, but was resolved; I'm not sure why it is still displaying.

![Screen Shot 2019-10-07 at 6 39 54 AM](https://user-images.githubusercontent.com/588335/66305438-5005ae00-e8cd-11e9-8a91-7617e17a449a.png)

Can you try another seed in production?

**Comment by nullhandle** [comment]
Well, I registered https://argo.stanford.edu/view/druid:qy068kt3406, but so far it's failed for reasons likely unrelated to the workflow.

SWAP indicates that there are multiple captures (https://swap.stanford.edu/*/https://www.stanford.edu), but every one of them I try gives me a 503 error.

**Comment by nullhandle** [comment]
Now that SWAP is no longer throwing 503 errors, I was able to rerun the thumbnail generation step for this registered seed. The workflow completed successfully, so it appears that we can successfully register seeds via Argo.

**Comment by justinlittman** [comment]
Nice.
