### ISSUE TITLE
cache credentials for downloader_dlss

### ISSUE THREAD

**Issue by nullhandle** [sul-dlss/was-registrar-app#168]
A downloader user has been added for one of SUL's Archive-It accounts. Username is "downloader_dlss"; password is the same as for the other downloader accounts. Could this user please be cached in the was-registrar-app configuration to enable it to retrieve crawls for this Archive-It account?

**Comment by ndushay** [comment]
did shared_configs PR, redeployed prod.  I believe that is all that's needed (?)
