### ISSUE TITLE
/queues (sidekiq GUI) doesn't display

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/was-registrar-app#190]

**Comment by mjgiarlo** [comment]
@ndushay Could not reproduce this. Seeing the GUI in both stage and prod:

* https://was-registrar-app-stage.stanford.edu/queues
* https://was-registrar-app.stanford.edu/queues

Were you connected to VPN? Close?

**Comment by ndushay** [comment]
maybe it was me not being on VPN.  🤷‍♀
