### ISSUE TITLE
thumbnail-generator : unable to reach dor-services-app

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/was-registrar-app#197]
553 web archive seeds have this error in the wasSeedPreassemblyWF:

```thumbnail-generator : unable to reach dor-services-app```

https://argo.stanford.edu/catalog?f%5Bexploded_tag_ssim%5D%5B%5D=webarchive+%3A+seed&f%5Bprocessing_status_text_ssi%5D%5B%5D=Registered

Previously, these items had 404 errors, but these became dor-services-app errors after I reset the thumbnail-generator step. Many of these items have been in an error state for multiple years.

**Comment by aaron-collier** [comment]
Initial issue here is incorrect config:

```
[3] pry(main)> Settings.dor_services.url
=> "https://dor-services-test.stanford.test"
```

Updated the symlink to point to the shared configs settings dir and now get:

```
[was@was-robots1-prod current]$ ROBOT_ENVIRONMENT=production ./bin/console
Loading config from /opt/app/was/was_robot_suite/releases/20200302163143/config/environments/production
[1] pry(main)> Settings.dor_services.url
=> "https://dor-services-prod.stanford.edu"
```

There is an additional metadata issue for @andrewjbtw to look into before this is closable

**Comment by andrewjbtw** [comment]
Closing as the dor-services-app issue is fixed. 

Data issues will be handled separately.
