### ISSUE TITLE
start-special-dissemination : unable to reach dor-services-app

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/was-registrar-app#198]
The start-special-dissemination step is failing in the wasDisseminationWF with the error:

```start-special-dissemination : unable to reach dor-services-app```

See https://argo.stanford.edu/view/druid:qv994rj9746

**Additional context**

I got to this error after manually editing the contentMetadata to add a resource_id attribute, which is required by the cocina model. It looks like we will need to fix this in order to accession new web archive objects.

May be related to #197, also an issue with connecting to dor-services-app.

**Comment by aaron-collier** [comment]
Initial issue here is incorrect config:

```
[3] pry(main)> Settings.dor_services.url
=> "https://dor-services-test.stanford.test"
```

Updated the symlink to point to the shared configs settings dir and now get:

```
[was@was-robots1-prod current]$ ROBOT_ENVIRONMENT=production ./bin/console
Loading config from /opt/app/was/was_robot_suite/releases/20200302163143/config/environments/production
[1] pry(main)> Settings.dor_services.url
=> "https://dor-services-prod.stanford.edu"
```

There is an additional metadata issue for @andrewjbtw to look into before this is closable

**Comment by aaron-collier** [comment]
This particular issue looks closable:

https://argo.stanford.edu/view/druid:qv994rj9746

**Comment by andrewjbtw** [comment]
Closing, as the dor-services-app connection is fixed.
