### ISSUE TITLE
end-was-crawl-preassembly : unable to reach dor-services-app

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/was-registrar-app#200]
[druid:hr667xs8693](https://argo.stanford.edu/view/druid:hr667xs8693) has the following error in the wasCrawlPreassemblyWF:

```
end-was-crawl-preassembly : unable to reach dor-services-app
```

Note that this error occurred in the last month, which means that this is related to recent work someone must have done (or that happened automatically).

Possibly related to #197 and #198, which are also errors reaching dor-services-app.

**Comment by aaron-collier** [comment]
Initial issue here is incorrect config:

```
[3] pry(main)> Settings.dor_services.url
=> "https://dor-services-test.stanford.test"
```

Updated the symlink to point to the shared configs settings dir and now get:

```
[was@was-robots1-prod current]$ ROBOT_ENVIRONMENT=production ./bin/console
Loading config from /opt/app/was/was_robot_suite/releases/20200302163143/config/environments/production
[1] pry(main)> Settings.dor_services.url
=> "https://dor-services-prod.stanford.edu"
```

There is an additional metadata issue for @andrewjbtw to look into before this is closable

**Comment by andrewjbtw** [comment]
Closing as the dor-services-app issue is fixed.

Data issues will be handles separately.
