### ISSUE TITLE
should there be okcomputer check for sidekiq workers?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/was-registrar-app#207]
akin to pre-assembly or preservation_catalog -- which have a simple bespoke okcomputer check to ensure workers are up.

**Comment by jcoyne** [comment]
This app always has zero resque workers...because it uses sidekiq 😆

**Comment by ndushay** [comment]
haha - same question, tho, no?  or does sidekiq spin 'em up on demand?

**Comment by ndushay** [comment]
@jermnelson you looked into this for other robots - is there a check that can be added in any form?  If so, maybe you could add it.  If not, please close this ticket.  Thanks!

**Comment by mjgiarlo** [comment]
@ndushay @jcoyne 

Some of our hosts do check the # of sidekiq workers through Nagios, but not through OKComputer. See this example: [the check](https://github.com/sul-dlss/puppet/blob/aa1f7e9b2d93b9d583d642c40e47a40e2f48934d/hieradata/node/dor-techmd-worker-qa-a.stanford.edu.eyaml#L65-L67) and [the Nagios integration](https://github.com/sul-dlss/puppet/blob/aa1f7e9b2d93b9d583d642c40e47a40e2f48934d/hieradata/node/dor-techmd-worker-qa-a.stanford.edu.eyaml#L21-L25).

So, do we want this in OKComputer or in Nagios or both? (It's currently in neither for was-registrar-app, but it'd be super to be consistent about this across our portfolio.)

**Comment by jcoyne** [comment]
I prefer we just use nagios for checks.  That makes it easier to debug when we see a problem in nagios.

**Comment by jcoyne** [comment]
@aaron-collier I think we should close this ticket without taking any action, can we just use nagios?

**Comment by mjgiarlo** [comment]
@jcoyne Should this ticket's title change `s/okcomputer/nagios/`? last I checked, nagios wasn't set up for sidekiq checks for WRA so there is work to be done.

**Comment by jcoyne** [comment]
@mjgiarlo sounds good to me. Should this be move to operations-tasks then?

**Comment by aaron-collier** [comment]
I'm happy to re-write/update or move to an ops task tomorrow. Sure thing.

**Comment by aaron-collier** [comment]
This was done already at:

https://github.com/sul-dlss/puppet/blob/production/hieradata/node/was-registrar-app.stanford.edu.eyaml#L95

**Comment by ndushay** [comment]
now to be super annoying -- do we have similar for all our other sidekiq apps?  (See FR sheet in dev playbook for a list)

**Comment by mjgiarlo** [comment]
@ndushay AFAIK, yes. Nagios checks were part of the sidekiq/systemd work I did across our portfolio.
