### ISSUE TITLE
map items with no <resource id=""> values in contentMetadata to cocina model

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/was-registrar-app#221]
The web archiving accessioning pipeline has not been assigning resource ids to files accessioned for seed and crawl objects. Resource id's are required for the Cocina models and enable addressing specific files directly.

I think the underlying issue has been fixed for newly-created crawl and seed objects. See https://github.com/sul-dlss/was_robot_suite/pull/196

What remains to be fixed are all of the existing crawl and seed objects that still lack resource ids.

Seed objects:
https://argo.stanford.edu/catalog?f%5Bis_governed_by_ssim%5D%5B%5D=info%3Afedora%2Fdruid%3Axt299pt7593&f%5BobjectType_ssim%5D%5B%5D=item

Crawl objects:
https://argo.stanford.edu/catalog?f%5Bis_governed_by_ssim%5D%5B%5D=info%3Afedora%2Fdruid%3Axt299pt7593&f%5BobjectType_ssim%5D%5B%5D=item

The most common naming convention SDR uses for most resource ids is the following

{druid}_{#}

The # is just an integer starting at 1 and incrementing by 1 for each file listed in the contentMetadata. I don't know of any reason to use another naming convention for web archiving objects. The format of the resource id does not seem to affect the public-facing display, but I'm not 100% certain of that.

**Examples**

I manually remediated a few seed objects last month:

https://argo.stanford.edu/catalog?f%5Baccessioned_latest_dttsi%5D%5B%5D=%5B2020-03-01T00%3A00%3A00.000Z+TO+2020-04-01T23%3A59%3A59.000Z%5D&f%5Bis_governed_by_ssim%5D%5B%5D=info%3Afedora%2Fdruid%3Axt299pt7593&f%5BobjectType_ssim%5D%5B%5D=item

Example resource id:

`resource id="cv098jq5318_1"`

**Next steps**

Given the ~20,000 items with this issue, we will need to find a way to script the remediation. It might require interacting with Fedora directly.

**Comment by justinlittman** [comment]
Why can't we just generate these on-the-fly when mapping to Cocina model? Why do they need to be persisted to Fedora?

**Comment by andrewjbtw** [comment]
If it can be mapped on the fly and not written into the contentMetadata (in Fedora or on disk), doesn't that mean resource ids aren't actually required? That would be ok, but I started from the information that resource ids are required.

**Comment by andrewjbtw** [comment]
Likely to be replace by cocina mapping.

**Comment by justinlittman** [comment]
For https://github.com/sul-dlss/dor-services-app/blob/master/app/services/cocina/dro_structural_builder.rb#L39, if `resource_node['id']` is null then construct as `{druid}_{index #}`.

**Comment by mjgiarlo** [comment]
@justinlittman :speech_balloon: 
> For [sul-dlss/dor-services-app:app/services/cocina/dro_structural_builder.rb@`master`#L39](https://github.com/sul-dlss/dor-services-app/blob/master/app/services/cocina/dro_structural_builder.rb#L39) [](/sul-dlss/dor-services-app/blob/HEAD@{2020-04-23T18:49:30Z}/app/services/cocina/dro_structural_builder.rb#L39), if `resource_node['id']` is null then construct as `{druid}_{index #}`.

Are you suggesting that making :point_up: change is sufficient to satisfy the need expressed in this issue? Does this need any further discussion? (For instance, how would we test this change?)

**Comment by justinlittman** [comment]
I believe that should be adequate. To test, a web crawl, e.g., https://argo-stage.stanford.edu/view/druid:ht470fs7890?beta=true should render without throwing a Honeybadger error.

**Comment by mjgiarlo** [comment]
@justinlittman It looks like that link might already render without throwing a HB error. At least, I don't see any HB errors after reloading that page. But the cocina model is pretty sparse, and I bet I can use that for testing. Thank you!

**Comment by justinlittman** [comment]
The page doesn't throw a 500, but it does send an HB alert. (I tested.)

**Comment by mjgiarlo** [comment]
@justinlittman :speech_balloon: 
> The page doesn't throw a 500, but it does send an HB alert. (I tested.)

Ah, it helps if you look at the right project. I was looking in Argo and shoulda been looking in DSA. Thanks for straightening me out, sir.

**Comment by andrewjbtw** [comment]
The other thing to test is running through the accessionWF. Items without the resource ids have been stalling in that workflow with a dor-services-app 500 error.
