### ISSUE TITLE
Click on hyperlink lead to screen shown "forbidden"

### ISSUE THREAD

**Issue by peterchanws** [sul-dlss/was-registrar-app#227]
Click druid:hr667xs8693 
in https://was-registrar-app.stanford.edu/collections/1/edit lead to screen shown "forbidden"

**Comment by andrewjbtw** [comment]
I believe this and https://github.com/sul-dlss/was-registrar-app/issues/226 are both related to permissions. I'm taking a look at the APOs and workgroups.

**Comment by andrewjbtw** [comment]
Added web archiving staff to all crawl and seed APOs, so you should be able to see those druids now.

**Comment by peterchanws** [comment]
It works now.
