### ISSUE TITLE
Unable to goto http://sul-swap-stage.stanford.edu/

### ISSUE THREAD

**Issue by peterchanws** [sul-dlss/was-registrar-app#228]
Try to go http://sul-swap-stage.stanford.edu/ and get the following:
<img width="1045" alt="Screen Shot 2020-05-06 at 9 41 25 AM" src="https://user-images.githubusercontent.com/1050899/81204256-db3b4500-8f7d-11ea-9c1e-2af541df2d48.png">

**Comment by justinlittman** [comment]
I've checked with Ops and the use of a self-signed certificate is deliberate. Can you try this with Firefox, which will allow you to proceed even though the certificate is self-signed?

**Comment by peterchanws** [comment]
Yes. It works under Firefox.
