### ISSUE TITLE
Accessioned collection shown in was-registrar not shown in Stanford Web Archive Portal

### ISSUE THREAD

**Issue by peterchanws** [sul-dlss/was-registrar-app#229]
The "Chinese Non-Governmental Organizations Web Archive" collection was accessioned as shown in https://was-registrar-app.stanford.edu/collections/1/edit

The following seeds included in the collection can be seen in Wayback but not shown in Stanford Web Archive Portal (The Resource you requested is not in this archive.)

http://www.njscszh.org/
www.tyjjh.org.cn/
www.qhcharity.org/

**Comment by justinlittman** [comment]
Looking in ArchiveIt, these sites were captured, but are still embargoed:

![image.png](https://images.zenhubusercontent.com/5d8270f64def500001d12f23/1d6611a3-291b-458a-86cf-ec6a39f50f61)

![image.png](https://images.zenhubusercontent.com/5d8270f64def500001d12f23/9c70ecc0-ab35-460b-8103-2ad0a82338ad)

![image.png](https://images.zenhubusercontent.com/5d8270f64def500001d12f23/61d1d81d-5d34-40d6-b149-56027e3ec20a)

**Comment by peterchanws** [comment]
Thanks. Will pay attend to the embargo terms in future.
