### ISSUE TITLE
Can't apply "webarchive:crawl" tag 

### ISSUE THREAD

**Issue by peterchanws** [sul-dlss/was-registrar-app#230]
"All newly-registered web archive crawl objects, regardless of processing status, should be bulk updated with the tag webarchive:crawl so that all web archive crawl objects can easily be faceted across APOs" https://consul.stanford.edu/display/WARC/Confirm+Crawl+Object+Accessioning+Completion

I tried using "edit Tag" to add "webarchive:crawl" tag in https://argo-stage.stanford.edu/view/druid:xz300ms9582

The system response "We're sorry, but something went wrong.
If you are the application owner check the logs for more information."

**Comment by justinlittman** [comment]
I was able to add it. Try "webarchive : crawl" (with spaces around :).

**Comment by peterchanws** [comment]
Thanks, Justin. I will update the consul page.
