### ISSUE TITLE
Accessioned item not shown in PURL or Searchworks

### ISSUE THREAD

**Issue by peterchanws** [sul-dlss/was-registrar-app#231]
I accession the collection "Ted Nelson Web Archive" through WAS registrar. Workflow for
https://argo-stage.stanford.edu/view/druid:xz300ms9582 are all completed. I can't see the item through PURL or Searchworks in the top left hand corner.

https://sul-purl-test.stanford.edu/druid:xz300ms9582
give
The item you requested does not exist.

**Comment by jcoyne** [comment]
@peterchanws I don't believe that the argo-stage environment is connected to the access teams (purl, stacks,searchworks) test environment.

**Comment by andrewjbtw** [comment]
It looks like the Purl links in the staging environment are directing to the wrong URL. The druid shouldn't be part of the URL but the links in argo-stage are being generated with it:

https://sul-purl-test.stanford.edu/xz300ms9582 takes you to the Ted Nelson Web Archive collection purl.

The stacks and purl test environments are connected to argo-stage and the SDR staging environment but searchworks is not.

**Comment by peterchanws** [comment]
@andrewjbtw Thanks, Andrew for the clarification. 
Is there a plan to fix the PURL link?

**Comment by andrewjbtw** [comment]
I just filed an Argo ticket to fix it https://github.com/sul-dlss/argo/issues/1996

It seems to be a recent problem.
