### ISSUE TITLE
No WARCs fetched noted in WAS-register for Stanford University Websites

### ISSUE THREAD

**Issue by peterchanws** [sul-dlss/was-registrar-app#234]
https://was-registrar-app.stanford.edu/collections/3/edit
No WARCs fetched noted in WAS-register for Stanford University Websites in many months. I checked one seed: https://amyblueaward.stanford.edu/
The site was successfully crawled and can be seen in wayback:
https://wayback.archive-it.org/5591/20190611010410/https://amyblueaward.stanford.edu/

**Comment by justinlittman** [comment]
As discussed, this collection is currently inactive. Hence, it is not retrieving WARCs.

**Comment by peterchanws** [comment]
I see. Thanks.
