### ISSUE TITLE
metadata-extractor : Error in executing the WASMetadataExtractor.jar pid 49722 exit 255

### ISSUE THREAD

**Issue by peterchanws** [sul-dlss/was-registrar-app#235]
https://was-registrar-app.stanford.edu/collections/3/edit
druid:zf985qg6496 created shown metadata-extractor error.
https://argo.stanford.edu/view/druid:zf985qg6496
If it is the program causing the error, please take a look.
If it is the metadata spreadsheet causing the error, please let me know how to download the spreadsheet.

**Comment by peterchanws** [comment]
Josh didn't create the collection in WAS. He suspected Nick did that. Since the collection cannot be found in Searchworks and SWAP,  I suggest we remove this collection from WAS.

**Comment by peterchanws** [comment]
There is no delete function in WAS. How can I remove this item?

**Comment by justinlittman** [comment]
I can delete it, but my preference would be to leave as inactive so there is a record of it. Would that be OK?

**Comment by peterchanws** [comment]
Sure. The "Stanford University Websites" collection consists of many websites. Josh and I agreed to start with a collection with fewer websites so that the QA would be easier. Once I can register in WAS, Argo with proper metadata in the stage environment, I will start working on production WAS.
