### ISSUE TITLE
Collection created using Web Archive Crawl Object Public APO Not in Argo

### ISSUE THREAD

**Issue by peterchanws** [sul-dlss/was-registrar-app#236]
I used Web Archive Crawl Object Public APO to create the collection "Game Preservation Projects"
System replied "Created collection druid:nc561qq3457
However, I can't find the druid:nc561qq3457 in Argo.
<img width="919" alt="Screen Shot 2020-05-11 at 2 39 58 PM" src="https://user-images.githubusercontent.com/1050899/81615123-f0590f00-9395-11ea-94c6-2af72651cfc0.png">
<img width="552" alt="Screen Shot 2020-05-11 at 2 40 23 PM" src="https://user-images.githubusercontent.com/1050899/81615133-f222d280-9395-11ea-9f1a-1e5af7991e3e.png">
<img width="623" alt="Screen Shot 2020-05-11 at 2 45 00 PM" src="https://user-images.githubusercontent.com/1050899/81615205-141c5500-9396-11ea-93fd-cc30e8d3aa47.png">

**Comment by jcoyne** [comment]
It looks to be right here in stage: https://argo-stage.stanford.edu/view/druid:nc561qq3457

**Comment by justinlittman** [comment]
I wonder if there is a slight latency after it is created and before it is available from search. @peterchanws you can always find an item by druid by substituting the druid in the URL: https://argo-stage.stanford.edu/view/druid:<druid here>

**Comment by peterchanws** [comment]
When I click the links https://argo-stage.stanford.edu/view/druid:nc561qq3457 or https://argo-stage.stanford.edu/view/druid I got "forbidden" in Chrome, Firefox and Safari. However, when I search druid:nc561qq3457 in https://argo-stage.stanford.edu/ already existed in Chrome, I got No results found for your search

**Comment by peterchanws** [comment]
Thanks, Andrew for the workgroup change. It works now.
