### ISSUE TITLE
Error in Register DOR Items

### ISSUE THREAD

**Issue by peterchanws** [sul-dlss/was-registrar-app#239]
I tried to register a crawl with 3 seeds for the collection Senses Places.
<img width="1530" alt="Screen Shot 2020-05-12 at 2 49 52 PM" src="https://user-images.githubusercontent.com/1050899/81756526-d17b7b00-9470-11ea-8fd2-34965c264000.png">
I got the same error for the crawl and 3 seeds 
build-was-crawl-druid-tree : No such file or directory - /was_unaccessioned_data/jobs/iaw/201510

<img width="1042" alt="Screen Shot 2020-05-12 at 4 52 19 PM" src="https://user-images.githubusercontent.com/1050899/81756583-fff95600-9470-11ea-8888-ae6bd57c121c.png">

**Comment by justinlittman** [comment]
@peterchanws Was this in stage or production?

**Comment by peterchanws** [comment]
in stage

**Comment by jcoyne** [comment]
It looks like there may have been some source_id validation problems: https://app.honeybadger.io/projects/50568/faults/63284869

**Comment by peterchanws** [comment]
I can't login https://app.honeybadger.io/projects/50568/faults/63284869 with my sunet id pchan3@stanford.edu. Could someone grant access for me?

**Comment by andrewjbtw** [comment]
It’s not registration that’s failing here. Registration succeeded in terms of creating the druids. The source_id conflict is the result of trying to register again with the same data. But registration doesn't need to be run again.

Instead, the problem is that the wasPreassemblyWF, which registration must automatically start, is running into an error. My guess is that there's supposed to be data placed at the file path that's being reported as not found. I'm not sure how that data gets there. Maybe it's supposed to be there before the object is registered.

**Comment by andrewjbtw** [comment]
On second thought, maybe I just don't understand what "registration" means to WAS. But for https://argo-stage.stanford.edu/view/jk890tf8873 (for example) it looks like the error is downstream of the registration form.

**Comment by jcoyne** [comment]
Sorry Peter, the link was for the infrastructure team. The error was:
`

ArgumentError: Source ID must follow the format 'namespace:value', not 'was_unaccessioned_data/jobs/iaw/201510'`

I'm not sure if that has anything to do with the problem you have here, but it seems curious that the id matched.

**Comment by peterchanws** [comment]
I followed the instructions in https://consul.stanford.edu/display/WARC/Initiating+Crawl+Object+Accessioning when creating the source id.
Should I use "iaw:201510" instead of iaw/201510?

**Comment by peterchanws** [comment]
Here is the screen print from Archive-It for the collection (6385) and crawl id (181129).
<img width="1135" alt="Screen Shot 2020-05-14 at 8 29 12 AM" src="https://user-images.githubusercontent.com/1050899/81954040-39d77300-95bd-11ea-9656-a03426baf190.png">

Here is the screen print from Archive-It on the seed url
<img width="1056" alt="Screen Shot 2020-05-14 at 8 30 47 AM" src="https://user-images.githubusercontent.com/1050899/81954129-54115100-95bd-11ea-93d5-c98e1e218e55.png">

**Comment by andrewjbtw** [comment]
@peterchanws The instructions you link to say they are for crawls that did not come from Archive-It.

**Comment by peterchanws** [comment]
@andrewjbtw Thanks. I missed that.
