### ISSUE TITLE
qa VM?  or remove shared_configs branch?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/was-registrar-app#251]
- was-registrar-app-qa is not in puppet
- there is an empty was-registrar-app-qa branch in shared_configs
- there is no qa deploy target in the app.

If we want a qa VM for this app, can we follow thru?

If we do NOT want a qa VM for this app, can we remove the shared_configs branch that has nothing useful in it?

**Comment by mjgiarlo** [comment]
We have a QA VM now. Fixed by #281.
