### ISSUE TITLE
Add data input validation to collection configuration form

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/was-registrar-app#309]
We need to improve validation of the data input into the collection configuration form. The values entered into this form are passed onto the wasapi downloader to fetch crawl data from Archive-IT. When the values are not valid, the retrieval fails. This happens mostly in the background and it can be difficult to track down and correct the errors.

Issues we have seen:

- leading and/or trailing spaces in one or more of the values (throws off validation of druid format, collection ids)
- incorrect or non-existent collection ids

**Comment by mjgiarlo** [comment]
We may or may not want to split "incorrect" collection identification to another ticket.

**Comment by lwrubel** [comment]
Thanks, @andrewjbtw. Collection druids don't get created via WRA, so the improvements here would be to:

* make sure that the collection druid that is entered exists and it is a collection
* handle leading and/or trailing spaces in one or more of the values, as originally described
