### ISSUE TITLE
Authenticate or authorize users

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/was-registrar-app#47]

**Comment by nullhandle** [comment]
Yes, it would be ideal if we could restrict the set of users who are able to initiate automated and recurring downloading and accessioning of web archive data, given the likely need for users to have some external awareness of free space on the staging volume and not setting active too many concurrent streams. Likely users will be limited at the start to the SDR Repository Manager, the Web Archivist, and the Web Archiving Service Manager.

**Comment by ndushay** [comment]
tagging @justinlittman re: disposition of this github issue.

**Comment by justinlittman** [comment]
The workgroups are:
* sdr:developer
* sdr:was-staff

**Comment by justinlittman** [comment]
https://github.com/sul-dlss/operations-tasks/issues/2015 is the ops request.
