### ISSUE TITLE
Allow WACZ files to be registered

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/was-registrar-app#475]
Make sure that one-time registration will take .wacz files rather than only .warc / .warc.gz files.

**Comment by lwrubel** [comment]
Need to determine what content type the WACZ should get registered a: object? webarchive-binary? file?

Note this affects downstream workflows.

**Comment by mjgiarlo** [comment]
@edsu @justinlittman Can this issue be closed now?

**Comment by edsu** [comment]
Yes, I think so!
