### ISSUE TITLE
Deprecate existing was-registrar

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/was-registrar-app#5]
- [x] shut down the VMs
- [ ] remove from dependency update script

**Comment by justinlittman** [comment]
Moved was-registrar repo to sul-dlss-deprecated.

**Comment by justinlittman** [comment]
https://github.com/sul-dlss/DevOpsDocs/pull/308 is for removing from DevOpsDocs.

**Comment by nullhandle** [comment]
@justinlittman Looks like this may have been completed?
