### ISSUE TITLE
Make minimum embargo 1 month

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/was-registrar-app#500]
As described in #486, there are situations where a crawl spans a month end/start or there is a delay between a test crawl being run and the decision to save it. This leads to the crawl missing getting downloaded/registered.

To avoid this, make the minimum embargo date possible 1 month instead of 0 months.

**Comment by peterchanws** [comment]
Confirmed with Josh - please make the minimum embargo date possible 1 month instead of 0 months.

**Comment by justinlittman** [comment]
Action for this ticket:
* Add validation to the model for a minimum of 1.
* Change the number input on the collection form for a minimum of 1.
* Change existing collections that have an embargo of 0 to 1.
