### ISSUE TITLE
Add client for WASAPI API interaction

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/was-registrar-app#52]
Related to #15

**Comment by jcoyne** [comment]
I'm not sure what this ticket means.  Does it mean "create a client gem that can speak to the was-registrar-app service"?

**Comment by justinlittman** [comment]
Sorry to have not been clearer on this, but we should try wrapping the our Java WASAPI client first. If for some reason that is problematic, we can make the case for using a different implementation. (I know the Archives Unleashed project uses WASAPI and I suspect is probably a Ruby client.)

**Comment by justinlittman** [comment]
Closing this, as wrapping wasapi downloader as part of #76
