### ISSUE TITLE
Do we need to be able to destroy a collection?

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/was-registrar-app#53]

**Comment by nullhandle** [comment]
I assume that what is meant by "collection" here is an Archive-It collection, not an SDR collection. If that's the case, then we don't need to be able to destroy a collection. Archive-It collections can't be deleted unless they have no associated crawls, in which case we would hope or expect that a user wouldn't configure it for download on our end. If a collection has any associated crawls, we would want to be able to retrieve and accession them via the app.

**Comment by ndushay** [comment]
tagging @justinlittman re: disposition of this github issue.

**Comment by justinlittman** [comment]
My intention is that the user can activate / deactivate a collection, but not delete it. If, for some compelling reason it was necessary to delete a collection model, a developer could do it with rails console. If that compelling reason happened more than once, this ticket can be reopened to add the feature.
