### ISSUE TITLE
On-demand transfer from Archive-IT to SDR

### ISSUE THREAD

**Issue by peterchanws** [sul-dlss/was-registrar-app#556]
I have an urgent request to transfer https://partner.archive-it.org/933/collections/5593 from Archive-IT to SDR. I have done the necessary setup in WAS https://was-registrar-app.stanford.edu/collections/83/edit. Could you perform a on-demand transfer? Sorry for the trouble!

**Comment by justinlittman** [comment]
@peterchanws When you say "on-demand transfer", do you mean that this is a new scheduled collection that you want to fetch immediately (rather than wait for the monthly fetch)?

**Comment by justinlittman** [comment]
It is already running:
![image](https://user-images.githubusercontent.com/588335/223468310-9b75b35d-67bb-4a3a-90d7-19e0198e7e5a.png)


Looks like it is part-way done:
![image](https://user-images.githubusercontent.com/588335/223467945-d1155fea-e3f6-4035-9c1c-f06264c1ea7d.png)
