### ISSUE TITLE
Change earliest “Fetch start year” to 1990

### ISSUE THREAD

**Issue by peterchanws** [sul-dlss/was-registrar-app#682]
In https://was-registrar-app.stanford.edu/, the earliest “Fetch start year” is 2009. However, we have purchased crawls performed by the Internet Archive dating back to 1996.

Please change the earliest “Fetch start year” in https://was-registrar-app.stanford.edu/ to 1990

**Comment by lwrubel** [comment]
Closed with https://github.com/sul-dlss/was-registrar-app/pull/683
