### ISSUE TITLE
Last successful fetch should be month and year only

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/was-registrar-app#70]
Currently it is a full date.

This should be implemented as such in the model as well as the edit page.

**Comment by jcoyne** [comment]
@justinlittman can you saw why a full date will not work?

**Comment by justinlittman** [comment]
If you look at the workflow as described in the proposal, crawls are fetched in one month chunks. Thus, the last successful fetch is always a month / year. (This isn't the date that the fetch occurred; it is the date of the content that was retrieved, which with the embargo is probably 6 months ago.)

Upon further reflection, this can still be a date in the db; however, the model should round any date that is set to the beginning of the month. Or, it can be modeled as a month and year.

**Comment by justinlittman** [comment]
Per #71, changing the way that this is modeled.
