### ISSUE TITLE
Determine how to use Argo to register non-WASAPI crawls

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/was-registrar-app#92]
Required for #6 

This ticket is to determine how to use Argo to register non-WASAPI crawls and initiate the workflow.

@nullhandle reports 2 problems:
1. Not able to correctly select the collection and APO combination (since the collection has a web seed APO, but the crawl item need a public or dark crawl APO).
```
One limitation, however, is that the collection cannot be specified at the time of registration. Almost all web archive crawls objects are governed by the “web archive crawl object public APO”, but the collections are governed by a variety of APOs. The Argo “register items” interface meanwhile only allows you to select collections governed by the chosen APO, since the more typical pattern is that the collection and its items are governed by the same APO.

This would mean that someone would always have to come back and update the collection information after-the-fact.
```

2. Error when registering
```
attempted to register a crawl from (production) argo register items interface this morning, with the crawl object public apo but no collection specified
```
![Screenshot-2019-8-22 Argo](https://user-images.githubusercontent.com/588335/63549710-d7e25500-c4e5-11e9-8d9e-47c0b6e73e03.png)

```
once i clicked "register item" it displayed the error icon to the left of the relevant row
on hover, it just shows "error" - not sure what to make of that
```

**Comment by peetucket** [comment]
- Argo requires a collection to register items
- The collections that show up in the drop-down menu are not those governed by the APO selected, they are simply those collection druids specified in the `administrativeMetadata` datastream for that APO.  You can add additional collection druids to that datastream as needed without affecting the relationship between the collections and the APO

**Comment by nullhandle** [comment]
The druids of web archive collections governed by the web archive seed object APO that were not registered under the web archive crawl object public APO (i.e., their druids are not already in the `administrativeMetadata` for the web archive crawl object public APO) should be added there, and the Consul documentation updated (per #6) to reflect that Argo is already a viable mechanism for initiating the wasCrawlPreAssembly workflow for locally-executed crawls.
