### ISSUE TITLE
Rights when registering?

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/was-registrar-app#96]
It appears that in the existing code, the rights are always set to dark when registering a crawl item: https://github.com/sul-dlss/was-registrar/blob/master/lib/was/registrar/register_crawl_object.rb#L16

Is that correct?

**Comment by justinlittman** [comment]
@peetucket Can you help puzzle this out?

**Comment by peetucket** [comment]
Yes, that appears to be true.  The way I read the code in `dor-services-app` that is handling registration, the rights are taken from the APO by default, but can be overridden for the particular item/collection being registered by passing in a new value in the `params` hash:

https://github.com/sul-dlss/dor-services-app/blob/master/app/services/registration_service.rb#L110-L114

**Comment by nullhandle** [comment]
If "dark" means "preserve = yes; publish = no; shelve = no", then that should only apply to the subset of web archive crawl objects registered under the dark APO; I don't know why was-registrar would have that hard-coded for all crawl objects. The behavior we want is for the rights-based access conditions to be set by the governing APO - i.e., with the public and dark crawl object APOs setting shelve to "yes" or "no" respectively.

**Comment by peetucket** [comment]
In Argo, this line just pulls the rights from the drop-down menu to pass to dor-services-app to do the registration:

https://github.com/sul-dlss/argo/blob/master/app/assets/javascripts/registration/register.js#L58 

so the drop-down menu will "win" regardless of what is in the APO

**Comment by peetucket** [comment]
> If "dark" means "preserve = yes; publish = no; shelve = no", then that should only apply to the subset of web archive crawl objects registered under the dark APO; I don't know why was-registrar would have that hard-coded for all crawl objects. The behavior we want is for the rights-based access conditions to be set by the governing APO - i.e., with the public and dark crawl object APOs setting shelve to "yes" or "no" respectively.

According to https://github.com/sul-dlss/dor-services-app/blob/master/app/services/registration_service.rb#L110-L114 you should be able to set the `rights` param value to "default" to have it inherit the value from the governing APO.

**Comment by peetucket** [comment]
And yes, "dark" does imply "preserve = yes; publish = no; shelve = no" and thus no PURL or shelved files.  Perhaps this is done because the WAS data is "shelved" and "published" through its own pipeline, and we didn't want to get a traditional PURL or put those files on the stacks?

**Comment by nullhandle** [comment]
Yeah, not sure. For either APO, we don't want a PURL for the crawl objects. For the crawl object public APO, we want the files shelved to the web archiving stacks.

**Comment by peetucket** [comment]
I’m going to guess (not based on code examination) that the WAS robots do not use the publish/shelve/preserve attributes to decide what to do, so those directives are to ensure the regular accessionWF robots do not operate on these files.

**Comment by justinlittman** [comment]
OK. Seems reasonable to leave as "dark" and if testing reveals a problem, can revisit.
